BG_COLOR = '#1A1A19'
FG_COLOR = 'white'

WIDTH = 600
HEIGHT = 280
CENTER_X = WIDTH / 2

FG_BUTTON = '#1A1A19'
BG_BUTTON = '#1A1A19'

LABEL_FONT = ("Sans", 16, "bold")
BUTTON_FONT = ("Sans", 16, "bold")
PATH_FONT = ("Sans", 12)

LABEL_JUSTIFY = 'left'

LABEL_WIDTH = None
BUTTON_WIDTH = 100
CONST_HEIGHT = 40

LABEL_ANCHOR = "w"
BUTTON_ANCHOR = "center"
